pre-commit:
  commands:
    clang-format-check:
      glob: "*.{c,h}"
      root: "refloat/"
      run: clang-format -i --dry-run --Werror {staged_files}
      skip: false
    clang-format-fix:
      glob: "*.{c,h}"
      root: "refloat/"
      stage_fixed: true
      run: clang-format -i {staged_files}
      skip: true

clang-format:
  commands:
    fix:
      glob: "*.{c,h}"
      root: "refloat/"
      run: clang-format -i {all_files}
